In [1]:
import numpy as np

In [16]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimesion
a.ndim

1

In [10]:
# Get Shape
b.shape

(2, 3)

In [13]:
# Get Type
a.dtype

dtype('int16')

In [17]:
# Get Size
a.itemsize

4

In [26]:
# Get Totoal Size
# a.size
# a.size * a.itemsize
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [28]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
# Get a specific element [r, c]

a[1][1]


9

In [38]:
# Get specific row 
# a[0]
# a[0, :]
a[0][:]

array([2, 9])

In [40]:
# Get secific column
a[:, 1]

array([2, 9])

In [42]:
# [startindex:endindex:stepsize]

a[0, 1:6:2]

array([2, 4, 6])

In [45]:
a[0, 1:-2:2]

array([2, 4])

In [46]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [49]:
a[:, 1] = [30,10]
print(a)

[[ 1 30  3  4  5  6  7]
 [ 8 10 10 11 12 20 14]]


## 3-D Array Example

In [65]:
b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
b.shape

(1, 4, 2)

## Initializing Different Types of Arrays

In [54]:
# All zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
# All ones matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [64]:
# Any Other number
np.full((2,2), 99, dtype="float")

array([[99., 99.],
       [99., 99.]])

In [66]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
np.random.rand(4,2,3)

array([[[0.18675722, 0.55496826, 0.78311618],
        [0.96478079, 0.17522216, 0.75710605]],

       [[0.38480581, 0.27246247, 0.55577266],
        [0.09250685, 0.29734854, 0.87980174]],

       [[0.4461691 , 0.92088068, 0.51771937],
        [0.96705677, 0.98281316, 0.36197624]],

       [[0.9498338 , 0.75749743, 0.09484876],
        [0.74238073, 0.1919104 , 0.83449973]]])

In [71]:
np.random.random_sample(a.shape)

array([[0.19149709, 0.86096834, 0.1250977 , 0.23111509, 0.65136335,
        0.68693183, 0.64709336],
       [0.38612727, 0.53695124, 0.42875221, 0.22565007, 0.64103946,
        0.56228204, 0.98940591]])

In [98]:
# Random Integer Values
np.random.randint(-11, 11, size=(3,3))

array([[ 6, -8,  5],
       [ 9, -7, -4],
       [-5,  0, -5]])

In [102]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [111]:
# my solution
test = np.identity(5)
test[:][:] = 1
test[1:-1, 1:-1] = [0]

test[2][2] = 9
print(test)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [121]:
# Keith solution

output = np.ones((5,5))
z = np.zeros((3,3))
z[1][1] = 9

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [122]:
befor = np.array([[1,2,3,4], [5,6,7,8]])
print(befor)

[[1 2 3 4]
 [5 6 7 8]]


In [133]:
after = befor.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


In [137]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [154]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(v1)
print(v2)

print(np.vstack((v1,v2)))

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [158]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking and Advanced Indexing

In [181]:
# Take just true values

print(filedata[filedata > 50])
print(filedata[:, [1]])

[196  75 766  75  55 999  78  76  88]
[[13]
 [42]
 [22]]


In [182]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])

In [185]:
# any value > 50 returns true
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [186]:
# all values have to be > 50
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [193]:
question = np.random.randint(0, 30, size=(6,5))
question

array([[ 7, 10,  4, 17, 23],
       [24,  7,  3, 15, 18],
       [18,  0, 21, 29,  4],
       [11,  4,  2,  4, 22],
       [ 2,  3, 27, 20, 22],
       [27, 10, 18, 17, 19]])

In [196]:
question[[0,1,2,3], [1,2,3,4]]

array([10,  3, 29, 22])

In [202]:
question[[0,4,5], 3:]

array([[17, 23],
       [20, 22],
       [17, 19]])