In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimesion
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get Totoal Size
# a.size
# a.size * a.itemsize
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# Get a specific element [r, c]

a[1][1]

9

In [11]:
# Get specific row 
# a[0]
# a[0, :]
a[0][:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get secific column
a[:, 1]

In [ ]:
# [startindex:endindex:stepsize]

a[0, 1:6:2]

In [ ]:
a[0, 1:-2:2]

In [ ]:
a[1,5] = 20
print(a)

In [ ]:
a[:, 1] = [30,10]
print(a)

## 3-D Array Example

In [ ]:
b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
b.shape

## Initializing Different Types of Arrays

In [12]:
# All zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# All ones matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [14]:
# Any Other number
np.full((2,2), 99, dtype="float")

array([[99., 99.],
       [99., 99.]])

In [15]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [16]:
np.random.rand(4,2,3)

array([[[8.79810053e-01, 7.70073820e-01, 7.18880560e-01],
        [6.32617305e-01, 1.70563287e-01, 8.29202479e-01]],

       [[4.03231331e-01, 3.65201711e-01, 7.89497368e-01],
        [5.44803431e-01, 7.33500089e-01, 8.01157156e-01]],

       [[4.48329336e-01, 2.34472095e-01, 9.42425074e-02],
        [4.44472675e-01, 6.97957734e-01, 2.93160270e-01]],

       [[4.33256698e-02, 2.36231572e-01, 5.48916474e-01],
        [3.43356724e-04, 3.58400938e-01, 1.18183597e-01]]])

In [17]:
np.random.random_sample(a.shape)

array([[0.13691268, 0.09253963, 0.5204893 , 0.96902973, 0.57790201,
        0.32051817, 0.98302026],
       [0.12921512, 0.95468019, 0.75391419, 0.4519654 , 0.34280646,
        0.36254636, 0.68686308]])

In [18]:
# Random Integer Values
np.random.randint(-11, 11, size=(3,3))

array([[ -5, -11, -11],
       [  2,  10,   3],
       [ -4,   7,   4]])

In [ ]:
# identity matrix
np.identity(4)

In [ ]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
r1

In [ ]:
# my solution
test = np.identity(5)
test[:][:] = 1
test[1:-1, 1:-1] = [0]

test[2][2] = 9
print(test)

In [ ]:
# Keith solution

output = np.ones((5,5))
z = np.zeros((3,3))
z[1][1] = 9

output[1:-1, 1:-1] = z
print(output)

In [ ]:
befor = np.array([[1,2,3,4], [5,6,7,8]])
print(befor)

In [ ]:
after = befor.reshape((2,4))
print(after)

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

In [19]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(v1)
print(v2)

print(np.vstack((v1,v2)))

[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [20]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking and Advanced Indexing

In [21]:
# Take just true values

print(filedata[filedata > 50])
print(filedata[:, [1]])

[196  75 766  75  55 999  78  76  88]
[[13]
 [42]
 [22]]


In [22]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])

In [23]:
# any value > 50 returns true
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [24]:
# all values have to be > 50
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [25]:
question = np.random.randint(0, 30, size=(6,5))
question

array([[11, 13,  0, 29, 11],
       [ 7, 14,  1, 13,  6],
       [12,  5, 17,  8, 25],
       [18,  7, 25, 24, 26],
       [ 4, 24, 18,  9, 25],
       [22, 22,  2, 18, 28]])

In [26]:
question[[0,1,2,3], [1,2,3,4]]

array([13,  1,  8, 26])

In [27]:
question[[0,4,5], 3:]

array([[29, 11],
       [ 9, 25],
       [18, 28]])

In [37]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [45]:
np.array([[1,2,3],[4,5,6]]).ndim

2

In [46]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x00000246367D3B80>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [48]:
np.info(np.arange(0))

class:  ndarray
shape:  (0,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x24635e0a180
byteorder:  little
byteswap:  False
type: int32


In [59]:
z = np.arange(1,9)
z

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
z.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [68]:
np.hsplit(z, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [71]:
np.vsplit(z, 1)

ValueError: vsplit only works on arrays of 2 or more dimensions